site_name: "Pakistan Honeynet Project"
site_url: "https://www.pakhoneynet.org"
theme:
  name: "material"
  # custom_dir: overrides
  favicon: images/favicon.ico
  logo: images/logo.png
  font:
    text: Segoe UI
  palette:
    primary: yellow
    accent: amber
markdown_extensions:
  - admonition
# Add this section
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/68B8Ru5fSU
      name: Discord Server
    
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/projecthoneynet
      name: Twitter
    
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/TheHoneynetProject/
      name: GitHub

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ProjectHoneynet
      name: Youtube
  
nav:
  - Home: index.md
  - Projects: projects.md
  - Research: research.md
  - Members: members.md
  - GSoC: gsoc/index.md
  - Reports: 
    - Overview: reports/index.md
    - 2025: reports/2025/index.md
  - Events: events/index.md


